name: customer_app
description: 'A new Flutter project.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_bloc: 9.1.1
  bloc_concurrency: 0.3.0
  dio: 5.9.0
  logger: 2.6.1
  json_annotation: 4.9.0
  flutter_spinkit: 5.2.2
  intl: 0.20.2
  freezed_annotation: 3.1.0
  get_it: 8.2.0
  go_router: 16.1.0
  equatable: 2.0.7
  connectivity_plus: 6.1.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  font_awesome_flutter: 10.10.0
  sentry_flutter: 9.6.0
  fluttertoast: 8.2.12
  flutter_svg: 2.2.0
  mi_country_picker: 0.0.6
  pinput: 5.0.1
  flutter_localizations:
     sdk: flutter
  country_code_picker: ^3.4.0
  country_picker: ^2.0.27
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  build_runner: 2.7.0
  json_serializable: 6.10.0
  freezed: 3.2.0
  import_sorter: 4.6.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - asset/images/
    - asset/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: asset/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: asset/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: asset/fonts/Poppins-Light.ttf
          weight: 300
        - asset: asset/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: asset/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: asset/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: asset/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: asset/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: asset/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: asset/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: asset/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: asset/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: asset/fonts/Poppins-Black.ttf
          weight: 900
        - asset: asset/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

